project:
  type: website

website:
  reader-mode: true
  page-footer:
    border: false
    background: dark
    foreground: primary
    left: "Copyright 2021, Norah Jones"
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/
  back-to-top-navigation: true
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Giới thiệu"
      - section: "Tản mạn"
      - section: "Học thuật"
        contents:
          - text: "Set theory"
            href: posts/Set theory/set_theory.qmd
          - text: "Group theory"
            href: posts/Group theory/group_theory.qmd
    background: light
    foreground: primary
    border: true
    favicon: "lcat.jpg"
  navbar:
    logo: "lcat.jpg"
    background: dark
    foreground: primary
    search: true
    left:
      - text: "About"
        href: about.qmd
  # (additional metadata excluded for brevity)
  margin-header: subscribe.html

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual